services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3
    ports:
      - "8000:8000"
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://19df-188-122-27-177.ngrok-free.app
      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT=Ov23li8sQZfgAQPOIq4m
      - WOODPECKER_GITHUB_SECRET=8c8f7d6148b52ee42bc84cac85c18623eb1687d9
      - WOODPECKER_AGENT_SECRET=8c8f7d6148b52ee42bc84cac85c18623eb1687d9
    restart: unless-stopped

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3
    depends_on:
      - woodpecker-server
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=8c8f7d6148b52ee42bc84cac85c18623eb1687d9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - woodpecker-agent:/etc/woodpecker
    restart: unless-stopped
  ngrok:
    image: ngrok/ngrok:3
    command: http woodpecker-server:8000 --log=stdout
    environment:
      - NGROK_AUTHTOKEN=3DXTay7O9a82Nk6uzNfJeW1tGE3_7CNGkHBvPnDSWguQRCUwL  # optional, for persistent tunnels
    ports:
      - "4040:4040"  # web interface to see public URL
    restart: unless-stopped

volumes:
  woodpecker-server-data:
  woodpecker-agent: