name: Django CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Zadanie 7: Anulowanie poprzednich workflow przy nowych commitach [cite: 111]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest # [cite: 14]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12 # [cite: 15]
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # Zadanie 7: Dodanie cache pip [cite: 108]
      - name: xd
        run: ls -la
      - name: Install Dependencies # [cite: 9]
        run: pip install -r ./mysite/requirements.txt
      - name: Basic Check
        run: python ./mysite/manage.py check
